### ISSUE TITLE
Decoding code crashes

### ISSUE THREAD

**Issue by ivmarkov** [esphome/esp-stacktrace-decoder#1]
The decoding code is full of `unwrap`s, which means that even the smallest decoding failure will result in a crash, instead of (at least) partially decoded stack trace.

For me, it crashes [here](https://github.com/maximeborges/esp-stacktrace-decoder/blob/main/src/lib.rs#L98).

I can provide you with an .ELF file and a stacktrace if necessary, but in general I believe (a) some of these errors (like unable to find a line and file) should be recoverable and (b) the others should probably be errors instead of panics.

**Comment by maximeborges** [comment]
Oh well, I was too eager to make it run in the browser, now I remember why I wanted to release it as a 0.1.0 first ^^'
I'll clean up a bit that mess

**Comment by ivmarkov** [comment]
By the way, the native decoding you've implemented (as in no dependency on Xtensa GCC's `addr2line`) might be a great addition to [espmonitor](https://github.com/esp-rs/espmonitor) and [espflash](https://github.com/esp-rs/espflash) (the latter seems to have [a minimal monitor itself lately](https://github.com/esp-rs/espflash/blob/master/cargo-espflash/src/line_endings.rs) - not sure why and not sure why in the `cargo` subcommand only).

@icewind1991 @kelnos @jessebraham ^^^

**Comment by kelnos** [comment]
Yeah, I have a local branch that uses the `addr2line` crate instead of shelling out to the binary.  One problem I've found is that `Context.find_frames()` often doesn't return anything, and you have to look at the symbol table from `Object` directly.  There are some lifetime/ownership issues with that approach that I hadn't yet worked out, and haven't had time recently to work on.

**Comment by maximeborges** [comment]
> One problem I've found is that Context.find_frames() often doesn't return anything

Do you have an example? The results I got for Arduino FW was on par with the outputs from the Java decoder that is using GDB

**Comment by maximeborges** [comment]
What do you think about PR #2 as a fix @ivmarkov  ?
Still a bit fresh on anything Rust, I think those modifications make sense but I'm not sure if it can be done better

**Comment by kelnos** [comment]
> > One problem I've found is that Context.find_frames() often doesn't return anything
> 
> Do you have an example? The results I got for Arduino FW was on par with the outputs from the Java decoder that is using GDB

Nothing I can easily share, but if you look at [the source for the addr2line example app](https://github.com/gimli-rs/addr2line/blob/master/examples/addr2line.rs#L237-L246), they include the fallback to the symbol table, which is how I figured out what I had to do to get my stuff working.

Edit: I guess I also mean [this part of the source](https://github.com/gimli-rs/addr2line/blob/master/examples/addr2line.rs#L268-L270).

**Comment by ivmarkov** [comment]
> What do you think about PR #2 as a fix @ivmarkov ? Still a bit fresh on anything Rust, I think those modifications make sense but I'm not sure if it can be done better

Look quite OK to me in general. I have a few minor nits, probably not worth mentioning.

A question: what is the format of the stack trace that can be parsed? Is the tool also accepting standard ESP32 Xtensa "Backtrace" formatting, generated either programmatically or on panics? I.e. `Backtrace:0x40183f44:0x3ffbaca0 0x400dfc16:0x3ffbacc0 0x400e3dd5:0x3ffbad30 0x400d787b:0x3ffbada0 0x400d61c1:0x3ffbb048 |<-CORRUPTED`?

**Comment by maximeborges** [comment]
At the moment it's only trying to parse any address in the 0x40xxxxxx range, like the Java thing is doing. I didn't even bother looking at the memory mappings for the ESP8266/32 since the code was supposedly working for both.  Also I couldn't find the format used for of the stack trace generated by the Arduino tool chain at least.
Definitely not the best solution I guess, but this started like a PoC to rewrite the thing in Rust and WASM, but I'd gladly make it more robust with your inputs. 

Also it was a bit late and I totally forgot to fix the WASM build...

**Comment by maximeborges** [comment]
Should be better now with v1.1.0, can you confirm ?

**Comment by ivmarkov** [comment]
Sorry, I did not have time to follow up with the original backtrace. I tried it with a few new ones, and I don't see any problem now (that is, with the command line executable).

For the wasm, what I would suggest is an error reporting when pressing the "Run" button, that I have not uploaded an elf file. It took me quite a few clicks on the Run button to realize that...
